# Generated by Django 5.0.4 on 2024-05-09 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BICSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=50, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('BRSTN', models.CharField(max_length=100)),
                ('BIC', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MCRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(default='', max_length=50)),
                ('date_issued', models.CharField(default='', max_length=100)),
                ('payee', models.CharField(default='', max_length=50)),
                ('amount', models.IntegerField(default='')),
                ('check_number', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('branch_remarks', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PesoNet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(default='', max_length=100)),
                ('OFI_reference_num', models.IntegerField(default='')),
                ('transact_amount', models.IntegerField(default='')),
                ('transact_date', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('branch_code', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier')], max_length=10)),
                ('branch_type', models.CharField(choices=[('head', 'Head Office'), ('camalig', 'Camalig Office'), ('daraga', 'Daraga Office'), ('manito', 'Manito Office'), ('legazpi', 'Legazpi Office')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
