# Generated by Django 5.0.4 on 2024-05-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_bicsetup_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcregister',
            name='branch',
            field=models.CharField(default='Default Branch', max_length=50),
        ),
    ]
