# Generated by Django 5.0.4 on 2024-05-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_pesonet_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch_type',
            field=models.CharField(blank=True, choices=[('head', 'Head Office'), ('camalig', 'Camalig Office'), ('daraga', 'Daraga Office'), ('manito', 'Manito Office'), ('legazpi', 'Legazpi Office')], max_length=20, null=True),
        ),
    ]
