# Generated by Django 5.0.4 on 2024-05-20 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20240520_1119'),
    ]

    operations = [
    ]
