# Generated by Django 5.0.4 on 2024-05-20 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20240520_1140'),
    ]

    operations = [
    ]
