# Generated by Django 5.0.4 on 2024-05-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20240520_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcregister',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pesonet',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
