# Generated by Django 5.0.4 on 2024-05-20 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_mcregister_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcregister',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
