# Generated by Django 5.0.4 on 2024-05-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_mcregister_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcregister',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='pesonet',
            name='branch_name',
        ),
        migrations.AlterField(
            model_name='mcregister',
            name='branch',
            field=models.CharField(default='', max_length=50),
        ),
    ]
