# Generated by Django 5.0.4 on 2024-05-21 01:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_remove_mcregister_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesonet',
            name='branch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pesonet',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch_type',
            field=models.CharField(blank=True, choices=[('Head Office', 'Head Office'), ('Camalig Office', 'Camalig Office'), ('Daraga Office', 'Daraga Office'), ('Manito Office', 'Manito Office'), ('Legazpi Office', 'Legazpi Office')], max_length=20, null=True),
        ),
    ]
