# Generated by Django 5.0.4 on 2024-05-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_pesonet_branch_alter_pesonet_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch_type',
            field=models.CharField(blank=True, choices=[('Head', 'Head Office'), ('Camalig', 'Camalig Office'), ('Daraga', 'Daraga Office'), ('Manito', 'Manito Office'), ('Legazpi', 'Legazpi Office')], max_length=20, null=True),
        ),
    ]
